[build]
  base = "client"
  command = "rm -rf node_modules && npm ci --legacy-peer-deps && npm run build && gulp licenses"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"
  ROLLUP_SKIP_NATIVE = "true"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
