[build]
  base = "client"
  command = "rm -rf node_modules package-lock.json && npm run install:client && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  ROLLUP_SKIP_NATIVE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
