[build]
  # Set the base directory to the client folder where your frontend app is located
  base = "client"
  
  # Build command for Vite
  command = "npm run build"
  
  # Publish directory (Vite's configured output directory)
  publish = "build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirect rules (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 