[build]
  base = "client"
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_SKIP_NATIVE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
