[build]
  base = "client"
  command = "rm -rf node_modules && npm ci --legacy-peer-deps && ROLLUP_SKIP_NATIVE=true vite build && gulp licenses"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_SKIP_NATIVE = "true"
  NODE_ENV = "production"

[dev]
  command = "rm -rf node_modules && npm ci --legacy-peer-deps && ROLLUP_SKIP_NATIVE=true vite build && gulp licenses"
  port = 3000
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
