[build]
  base = "client"
  command = "npm run install:client && npm run build"
  publish = "dist"  # Vite outputs to dist/ by default

[build.environment]
  NODE_VERSION = "18"
  ROLLUP_SKIP_NATIVE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
