# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    working_directory: hhsb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  deploy-job:
    working_directory: hhsb

    steps:
      - run:
          name: Set AWS region
          command: aws configure set region us-east-1

      - run:
          name: Configure CDN true
          command: aws configure set preview.cloudfront true

      - run:
          name: Set invalidation
          command: aws configure set preview.create-invalidation true

      - run:
          name: Deploy to S3 if tests pass and branch is develop
          command: aws s3 sync build/ s3://web.hiphopscoreboard.com/ --delete

      - run:
          name: Trigger CDN invalidation
          command: aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E3RIU72B7OZJRL\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: develop