version: 2
jobs:
  build-job-and-deploy:
    docker:
      - image: circleci/node

    environment:
     - NODE_ENV: "production"

    working_directory: ~/tmp/hhsb

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          name: Download and cache dependencies
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install npm weee
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run build

      - run:
          name: Install and configure AWS CLI
          command: |
            sudo apt-get -y -qq install awscli
            aws configure set region us-east-1
            aws configure set preview.cloudfront true
            aws configure set preview.create-invalidation true

      - run:
          name: Sync folder/files s3
          command: |
            aws s3 sync ~/tmp/hhsb/build s3://web.hiphopscoreboard.com/ --delete
            aws s3 sync ~/tmp/hhsb/build s3://www.hiphopscoreboard.com/ --delete

      - run:
          name: Trigger CDN invalidation for web.hiphopscoreboard.com and www.hiphopscoreboard.com
          command: |
            aws cloudfront create-invalidation --invalidation-batch "{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}" --distribution-id E3RIU72B7OZJRL
            aws cloudfront create-invalidation --invalidation-batch "{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}" --distribution-id E1M8PK1KN3UF5G

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job-and-deploy:
          filters:
            branches:
              only: develop